#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 "discord"
bspc config border_width 2.00
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config border_radius 1.00

bspc config top_padding 25
bspc config bottom_padding 25
bspc config left_padding 25
bspc config right_padding 25

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer false

bspc config normal_border_color "#F0C9F4"
bspc config focused_border_color "#C22BD2"

pactl load-module module-equalizer-sink &
sxhkd &
picom &
~/.fehbg &
~/.config/polybar/launch.sh &
~/.config/polybar_autohide/polybar-autohide &
eww open clock &
eww open greet &
redshift -l 13.757707499999999:109.1523409 -P -O 5000 &
fcitx5 &
bspc rule -a discord desktop='discord'
